# Automatically generated by makegen (https://github.com/aldahick/makegen)
COMPILER = g++
COMPILER_FLAGS = -std=c++11
COMPILER_HEADERS = 
COMPILER_LIBRARIES = 
OBJECT_FILES = obj/main.o
OUTPUT_FILE = bin/find
all: mkdirs $(OBJECT_FILES)
	$(COMPILER) $(COMPILER_FLAGS) $(COMPILER_HEADERS) $(OBJECT_FILES) -o $(OUTPUT_FILE) $(COMPILER_LIBRARIES)
obj/main.o: 
	$(COMPILER) $(COMPILER_FLAGS) $(COMPILER_HEADERS) -c ./src/main.cpp -o obj/main.o $(COMPILER_LIBRARIES)
clean:
	rm -rf $(OUTPUT_FILE)
	rm -rf $(OBJECT_FILES)
mkdirs:
	mkdir -p obj
	mkdir -p bin
